@extends('master')
@section('title','Checkout')
@section('loginheader')
@include('sections.loginheader')
@stop
@section('header-bottom')
@include('sections.header-bottom')
@stop
@section('header')
@include('sections.header')
@stop
@section('checkout')
@include('sections.checkout')
@stop