@extends('master')
@section('title','Home')
@section('loginheader')
@include('sections.loginheader')
@stop
@section('header-bottom')
@include('sections.header-bottom')
@stop
@section('header')
@include('sections.header')
@stop
@section('slider')
@include('sections.slider')
@stop
@section('category')
@include('sections.category')
@stop
@section('brand')
@include('sections.brand')
@stop
@section('price-range')
@include('sections.price-range')
@stop
@section('feature-items')
@include('sections.feature-items')
@stop
@section('category-tab')
@include('sections.category-tab')
@stop
@section('recommended-items')
@include('sections.recommended-items')
@stop
@section('ads-image')
@include('sections.ads-image')
@stop