@extends('master')
@section('title','Product-Details')
@section('middle')
@include('sections.header-middle')
@stop
@section('header')
@include('sections.header')
@stop
@section('category')
@include('sections.category')
@stop
@section('brand')
@include('sections.brand')
@stop
@section('price-range')
@include('sections.price-range')
@stop
@section('ads-image')
@include('sections.ads-image')
@stop
@section('product-details')
@include('sections.product_details')
@stop