@extends('master')
@section('title','Product')
@section('loginheader')
@include('sections.loginheader')
@stop
@section('header-bottom')
@include('sections.header-bottom')
@stop
@section('header')
@include('sections.header')
@stop
@section('advertisement-slider')
@include('sections.advertisement-slider')
@stop
@section('category')
@include('sections.category')
@stop
@section('brand')
@include('sections.brand')
@stop
@section('price-range')
@include('sections.price-range')
@stop
@section('ads-image')
@include('sections.ads-image')
@stop
@section('product')
@include('sections.product')
@stop
